# Use the official Python image as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application files to the container
COPY . /app

# Install any dependencies your application needs
RUN pip install -r requirements.txt

# Expose the port your app runs on
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:8000", "--workers", "3"]
